# Ğ°Ğ²Ñ‚Ğ¾ÑÑ‚Ğ°Ñ€Ñ‚ Power Supply 24Ğ’ Ğ”Ğ¸Ğ¾Ğ´Ğ½Ğ°Ñ Ğ¿Ğ¾Ğ´ÑĞ²ĞµÑ‚ĞºĞ°
- id: '1761053596139'
  alias: Ğ°Ğ²Ñ‚Ğ¾ÑÑ‚Ğ°Ñ€Ñ‚ Power Supply 24Ğ’ Ğ”Ğ¸Ğ¾Ğ´Ğ½Ğ°Ñ Ğ¿Ğ¾Ğ´ÑĞ²ĞµÑ‚ĞºĞ°
  description: Ğ’ĞºĞ»ÑÑ‡ĞµĞ½Ğ¸Ğµ Ğ±Ğ»Ğ¾ĞºĞ° Ğ¿Ğ¸Ñ‚Ğ°Ğ½Ğ¸Ñ Ñ Ğ´Ğ¸Ğ¾Ğ´Ğ½Ñ‹Ğ¼ Ğ¾ÑĞ²ĞµÑ‰ĞµĞ½Ğ¸ĞµĞ¼
  triggers:
    - trigger: homeassistant
      event: start
  conditions: []
  actions:
    - delay: "00:00:10"        # Ğ´Ğ°Ñ‘Ğ¼ ÑĞ¸ÑÑ‚ĞµĞ¼Ğµ Ğ¿Ğ¾Ğ´Ğ½ÑÑ‚ÑŒÑÑ
    - action: switch.turn_on
      target:
        entity_id: switch.system_diod
  mode: single

# Ğ°Ğ²Ñ‚Ğ¾ÑÑ‚Ğ°Ñ€Ñ‚ Ğ¢Ñ‘Ğ¿Ğ»Ñ‹Ğ¹ ĞŸĞ¾Ğ»
- id: '1761053833054'
  alias: Ğ°Ğ²Ñ‚Ğ¾ÑÑ‚Ğ°Ñ€Ñ‚ Ğ¢ĞµĞ¿Ğ»Ñ‹Ğ¹ ĞŸĞ¾Ğ»
  description: Ğ’ĞºĞ»ÑÑ‡ĞµĞ½Ğ¸Ğµ Ñ‚Ñ‘Ğ¿Ğ»Ğ¾Ğ³Ğ¾ Ğ¿Ğ¾Ğ»Ğ° Ğ¿Ñ€Ğ¸ Ğ²ĞºĞ»ÑÑ‡ĞµĞ½Ğ¸Ğ¸ HASS
  triggers:
    - trigger: homeassistant
      event: start
  conditions: []
  actions:
    - delay: "00:00:12"        # Ğ²ĞºĞ»ÑÑ‡Ğ°ĞµĞ¼ Ñ‡ÑƒÑ‚ÑŒ Ğ¿Ğ¾Ğ·Ğ¶Ğµ Ğ¿Ğ¾Ğ´ÑĞ²ĞµÑ‚ĞºĞ¸
    - action: switch.turn_on
      target:
        entity_id: switch.system_teply_pol
  mode: single

# Ğ£Ğ²ĞµĞ´Ğ¾Ğ¼Ğ»ĞµĞ½Ğ¸Ğµ Ğ¾ ÑÑ‚Ğ°Ñ€Ñ‚Ğµ HASS Ğ² Telegram (Ğ±ĞµĞ· Ğ¸Ğ½Ñ„Ğ¾Ñ€Ğ¼Ğ°Ñ†Ğ¸Ğ¸ Ğ¾ Ñ€ĞµĞ·ĞµÑ€Ğ²Ğ½Ğ¾Ğ¹ ĞºĞ¾Ğ¿Ğ¸Ğ¸)
- id: '1761122347275'
  alias: Ğ£Ğ²ĞµĞ´Ğ¾Ğ¼Ğ»ĞµĞ½Ğ¸Ğµ Ğ¾ ÑÑ‚Ğ°Ñ€Ñ‚Ğµ HASS Ğ² Telegram
  description: ĞÑ‚Ğ¿Ñ€Ğ°Ğ²ĞºĞ° ÑĞ¾Ğ¾Ğ±Ñ‰ĞµĞ½Ğ¸Ñ Ğ¿Ñ€Ğ¸ Ğ·Ğ°Ğ¿ÑƒÑĞºĞµ Home Assistant
  triggers:
    - trigger: homeassistant
      event: start
  conditions: []
  actions:
    - delay: "00:00:08"  # Ğ´Ğ°Ñ‘Ğ¼ ÑĞµÑ€Ğ²Ğ¸ÑÑƒ telegram_bot Ğ¿Ğ¾Ğ»Ğ½Ğ¾ÑÑ‚ÑŒÑ ÑÑ‚Ğ°Ñ€Ñ‚Ğ¾Ğ²Ğ°Ñ‚ÑŒ
    - action: telegram_bot.send_message
      data:
        config_entry_id: 01K85FEY9X86ZAEWBEGMWJEJ7V
        target:
          - '374673383'
        message: >-
          âœ… Home Assistant Ğ·Ğ°Ğ¿ÑƒÑ‰ĞµĞ½
          ğŸ•’ Ğ’Ñ€ĞµĞ¼Ñ Ğ·Ğ°Ğ¿ÑƒÑĞºĞ°: {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
    - action: persistent_notification.create
      data:
        title: "âœ… HASS Ğ·Ğ°Ğ¿ÑƒÑ‰ĞµĞ½"
        message: >-
          ğŸ•’ Ğ’Ñ€ĞµĞ¼Ñ Ğ·Ğ°Ğ¿ÑƒÑĞºĞ°: {{ now().strftime('%H:%M:%S %Y-%m-%d') }}
  mode: single