
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include_dir_merge_list includes/automations
script: !include scripts.yaml
scene: !include scenes.yaml
modbus: !include includes/modbus.yaml

homeassistant:
  customize: !include customize.yaml   # <-- переносим сюда
  packages: !include_dir_merge_named includes/packages


#Telegram
#api_key_bot: "2140345378:AAGNyUXaSRtgiIRU9hQTI-jFTAIt5lzHMaw"
#telegram_id_vital: "374673383"
#telegram_id_oksana: "496868345"

shell_command:
  ha_gitpush: "/bin/bash /config/ha_gitpush.sh"

panel_custom:
  - name: server_state
    sidebar_title: 'System'
    sidebar_icon: mdi:server
    js_url: /api/hassio/app/entrypoint.js
    url_path: 'hassio/system'
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator

recorder:
  db_url: mysql://homeassistant:AmYmyDFnL5@core-mariadb/homeassistant?charset=utf8mb4
#  auto_purge: true
#  purge_keep_days: 7            # оставляем 7 суток (подстрой под себя)
#  commit_interval: 1
#  exclude:
#    domains:
#      - automation
#      - updater
#    entities:
#      - sensor.time
#      - sensor.date
